### ISSUE TITLE
Add Error count / Error rate to Performance overview header

### ISSUE THREAD

**Issue by leathej1** [k6io/cloud-feature-requests#10]
As I am running a performance test in the cloud, I need to see new errors at a glance at the top of the test results page.

![2021-03-10 11_02_49-Window](https://user-images.githubusercontent.com/24658347/110677903-ee690380-8192-11eb-9b2a-0fe8821386d0.jpg)

**Comment by robingustafsson** [comment]
Yeah, this is something that's been missing for quite a while. We had to complete https://github.com/loadimpact/k6/issues/1828 (which needed some discussion 😅) first which will land in k6 v0.31.0 due out this week. Once that's out of the way, we'll start working on bringing this to the cloud. We'll likely implement this as an additional graph in the main chart that shows the failure rate. Perhaps also as a "Total errors" counter where there's apparently free real estate 😄

**Comment by sniku** [comment]
@leathej1 The "HTTP failures" metric (http_req_failed) has been released a few weeks ago in k6 [0.31.1](https://k6.io/blog/k6-v0.31/). HTTP failures are now also displayed in the app in the top header and on the main chart. :tada: 

![image](https://user-images.githubusercontent.com/442646/115848782-8b6ebb80-a424-11eb-9c24-14c0a6ac7960.png)

Keep these requests coming! :smile:
