### ISSUE TITLE
Scheduled test off by +1 hour

### ISSUE THREAD

**Issue by leathej1** [k6io/cloud-feature-requests#21]
Given my time zone of Arizona:
![2021-04-22 07_35_43-Window](https://user-images.githubusercontent.com/24658347/115733526-d5c93d00-a33d-11eb-8cae-be0c5927e423.jpg)

And my sheduled test time of 3:00 AM:
![2021-04-22 07_36_18-Window](https://user-images.githubusercontent.com/24658347/115733579-deba0e80-a33d-11eb-915d-24d7bdcc9c51.jpg)

I should expect to see my test start at 3:00 AM. Instead it is starting at 4:00 AM.
![2021-04-22 07_36_07-Window](https://user-images.githubusercontent.com/24658347/115733622-e7124980-a33d-11eb-8b6b-ac3dfd713f23.jpg)
![2021-04-22 07_38_07-Window](https://user-images.githubusercontent.com/24658347/115733632-e8437680-a33d-11eb-805a-528529fdf8d3.jpg)

**Comment by w1kman** [comment]
Unfortunately, the time zone used for Arizona is wrong (Mountain Daylight Time).
I've created a ticket for changing it to Mountain Standard Time.

**Comment by leathej1** [comment]
Arizona is really its own time zone since we do not observe Daylight Savings. You probably need a timezone picker lib that supports this.
